### ISSUE TITLE
Add StronglyTypedId<T> generic attribute for C# 11+

### ISSUE THREAD

**Issue by kzu** [andrewlock/StronglyTypedId#129]
Now that [C# (11+) supports generic attributes](https://learn.microsoft.com/en-us/dotnet/csharp/advanced-topics/reflection-and-attributes/generics-and-attributes), it would be nice to be able to annotate a type with the generic version to specify the backing type:

```csharp
[StronglyTypedId<int>]
public partial struct UserId { }
```

**Comment by andrewlock** [comment]
Thanks for the suggestion, but unfortunately this won't work with the new design. The backing type isn't an unconstrained type, it's one of a specific enum values, or a string. This was discussed further in #102.

**Comment by kzu** [comment]
Hm, it's kinda losing its original simplicity-focused approach.
