### ISSUE TITLE
Support for UUIDv7

### ISSUE THREAD

**Issue by mohaaron** [andrewlock/StronglyTypedId#142]
Are there any plans to implement UUIDv7 as an Id type?

**Comment by andrewlock** [comment]
Not currently. But you could do this in your own app by creating your own template, as described in [this post](https://andrewlock.net/updates-to-the-stronglytypedid-library/) and [this issue](https://github.com/andrewlock/StronglyTypedId/issues/102) 🙂

**Comment by andrewlock** [comment]
>... This does not produce the 350 lines of code that the built-in templates generate

Correct, your template has to include _everything_ you want - you could start from one of [the built-in templates ](https://github.com/andrewlock/StronglyTypedId/blob/master/src/StronglyTypedIds.Templates/guid-full.typedid) for example

> Code produced by template: Notice the extra } at the end? 

It's not "extra" the indenting is just a bit wonky 😄  The final `}` comes from the `mespace MarineEAM.Data.Models.WorkOrders
{`

If you indent all your code in your template, it'll look pretty again 😄

**Comment by mohaaron** [comment]
Thank you, I appreciate your feedback

**Comment by mohaaron** [comment]
@andrewlock, I do have one more question. The templates that use the full name have both Dapper and EntityFramework dependencies. If I were to use the guid-full template and I did not have Dapper installed wouldn't the generated code fail with a build error?

**Comment by andrewlock** [comment]
Yes, it would😊 the same goes if you use some of the other converters or IDs that have external dependencies. This is where the templates come in, you can tailor what you need to your requirements 😊
