### ISSUE TITLE
Prevent empty values

### ISSUE THREAD

**Issue by Palpie** [andrewlock/StronglyTypedId#143]
I would like an option to prevent empty values. With the option you would not have the `Empty` field and trying to create a new instance with an empty value would result in an ArgumentException being thrown.

**Comment by andrewlock** [comment]
You can kind of do this by creating your own template, as described in [this post](https://andrewlock.net/updates-to-the-stronglytypedid-library/) and [this issue](https://github.com/andrewlock/StronglyTypedId/issues/102) 🙂 

One problem you will have is that you can still always create an instance of the type with the `default` keyword.
