### ISSUE TITLE
char identity

### ISSUE THREAD

**Issue by dzmitry-lahoda** [andrewlock/StronglyTypedId#19]
emojis are very versatile now in unicode - may be there is patter for meta identity?

**Comment by andrewlock** [comment]
I'm very late to this, but the big redesign of the library in this PR is intended to make it easier to add any features you require: 
- https://github.com/andrewlock/StronglyTypedId/pull/117

The main idea is to make the library much more maintainable while also giving people a mechanism to customise the generated IDs as much as they like. This should make it easy for you to use features like this.
