### ISSUE TITLE
Port to System.Text.Json and target .NET 5

### ISSUE THREAD

**Issue by dzmitry-lahoda** [andrewlock/StronglyTypedId#21]
because System.Text.Json will work only there

**Comment by andrewlock** [comment]
This already supports System.Text.Json - no need to target .NET 5? System.Text.Json [supports loads of frameworks](https://www.nuget.org/packages/System.Text.Json/4.7.2).

**Comment by dzmitry-lahoda** [comment]
Cool. Generator have one.
