### ISSUE TITLE
Add XML documentation to generated code, or disable warning for each file at top

### ISSUE THREAD

**Issue by wforney** [andrewlock/StronglyTypedId#27]
Need to disable CS1591 per file in generated code, and possibly tag with a generated code attribute to make VS ignore issues in generated files.

**Comment by andrewlock** [comment]
I've released [a beta version](https://www.nuget.org/packages/StronglyTypedId/1.0.0-beta01) of a major update to the library converts to using Source generators. There's quite a few breaking changes in the release, so please make sure to check the release notes for how to update, but I'd appreciate any feedback you have before I do a final release! I've added this in the release

I've also written a blog post announcing the update that goes into a bit more details: https://andrewlock.net/rebuilding-stongly-typed-id-as-a-source-generator-1-0-0-beta-release

Thanks! 🙂

**Comment by andrewlock** [comment]
I've added the autogenerated xml attributes to the generated code which should solve this. Let me know if you still have any issues!
