### ISSUE TITLE
[Proposal] Add Parse and TryParse methods for Guid/long/int-backed ids

### ISSUE THREAD

**Issue by hankovich** [andrewlock/StronglyTypedId#30]
Hi, thanks for the handy library. I think it would be rather nice to have `Parse` method to do 
```csharp
UserId.Parse("some guid")
``` 

instead of 

```csharp
new UserId(Guid.Parse("some guid"))
```

And I'd like to also see `TryParse` to make my parsing safer.

**Comment by lucasteles** [comment]
This wold help to use the Id in aspnet minimal api route parameter

**Comment by lucasteles** [comment]
I opened a PR with an implementation proposal for this https://github.com/andrewlock/StronglyTypedId/pull/85

**Comment by andrewlock** [comment]
I'm very late to this, but I've included it in the big redesign of the library in this PR: 
- https://github.com/andrewlock/StronglyTypedId/pull/117

The main idea is to make the library much more maintainable while also giving people a mechanism to customise the generated IDs as much as they like.
