### ISSUE TITLE
Roslyn Source Code Generator

### ISSUE THREAD

**Issue by ignatandrei** [andrewlock/StronglyTypedId#34]
Hello
What about refactoring the code on https://devblogs.microsoft.com/dotnet/introducing-c-source-generators/  ?

( The AArnot code generator is now obsolete)

I want to put into my list of examples - https://github.com/ignatandrei/RSCG_Examples

**Comment by dzmitry-lahoda** [comment]
https://github.com/andrewlock/StronglyTypedId/issues/16

**Comment by ignatandrei** [comment]
Waiting for this ;-)

**Comment by andrewlock** [comment]
I've released a I've released [a beta version](https://www.nuget.org/packages/StronglyTypedId/1.0.0-beta01) of a major update to the library that converts to using Source generators. There's quite a few breaking changes in the release, so please make sure to check the release notes for how to update, but I'd appreciate any feedback you have before I do a final release!

I've also written a blog post announcing the update that goes into a bit more details: https://andrewlock.net/rebuilding-stongly-typed-id-as-a-source-generator-1-0-0-beta-release

Thanks! 🙂

**Comment by andrewlock** [comment]
I've just merged the spike I was working on for source generators, so I'll close this for now. It's still in before as I want to fix/explore a few things before full 1.0.0, but I'd appreciate any feedback you have after trying it out

**Comment by ignatandrei** [comment]
It is released on nuget?

**Comment by andrewlock** [comment]
@ignatandrei - yep 🙂  https://www.nuget.org/packages/StronglyTypedId/1.0.0-beta05

**Comment by ignatandrei** [comment]
I will try ASAP
