### ISSUE TITLE
[Proposal] Add attribute on entity, not on separate struct

### ISSUE THREAD

**Issue by ZlobnyiSerg** [andrewlock/StronglyTypedId#48]
Your approach requires some bit of code that could be omitted, I believe. My way is something like:
```csharp
[StronglyTypedId]
public partial class Foo {
  public IdType Id { get;set; }
}
```
compiles to:
```csharp
public partial class Foo {
  public struct IdType {
    // Implementation here
  }
}
```

**Comment by ZlobnyiSerg** [comment]
The only disadvantage I see is code completion. In my proposal no code suggesions will appear because IdType will be unknown type until you'll compile the code. On other side we can always write attribute first, then compile.

**Comment by andrewlock** [comment]
> The only disadvantage I see is code completion

I see two main disadvantages:

1. The source generator would have to be more complicated
2. It introduces ambiguity in the consuming code. Which types should be generated? Does it have to have a special type name, a special property name? Would fields work?

That second point is of significant concern for me, just to save a few key strokes. I wouldn't want to introduce that degree of indirection and ambiguity, so I'm going to close this for now. But thanks for the suggestion! 🙂
