### ISSUE TITLE
Support .net core 3.0

### ISSUE THREAD

**Issue by xaviergxf** [andrewlock/StronglyTypedId#5]
HI @andrewlock,

Do you have any plans to support .net core 3.0?

Thanks

**Comment by andrewlock** [comment]
Tooling is changing in .NET Core 3.0 as far as I know. Once  [CodeGeneration.Roslyn](https://github.com/AArnott/CodeGeneration.Roslyn) supports .NET Core 3.0, I will add support here

**Comment by darbio** [comment]
Any update on this? It seems that [ CodeGeneration.Roslyn supports .NET Core 3.x](https://github.com/AArnott/CodeGeneration.Roslyn/issues/177)

**Comment by andrewlock** [comment]
I haven't looked into it yet, but thanks for the heads up! I'll look into updating it when I get a chance.

As an aside, I'm struggling a bit with the StronglyTypedId NuGet package - for some reason I can't actually seem to get it to work properly, no matter what I try, hence the lack of movement here 🙁

**Comment by darbio** [comment]
What’s happening?

**Comment by andrewlock** [comment]
Thanks to @vebbo2 for implementing this, I'll push out a release to NuGet shortly
