### ISSUE TITLE
[Sugestion] Add Parameterless Constructor to EfCoreValueConverter

### ISSUE THREAD

**Issue by LeonLeitheusser** [andrewlock/StronglyTypedId#50]
With EF Core 6 the possibility of global conversions was introduced. But to set them up a parameterless Constructor is needed.
Currently this Feature is not documented but a pullrequest is on the way: [https://github.com/dotnet/EntityFramework.Docs/pull/3716/commits](url). The only change needed to get it to work ist adding the parameterless constructor to the EfCoreValueConverter. After that the only thing the user has to do ist to add the converters in the ConfigureConventions method override.

**Comment by andrewlock** [comment]
Great, thanks, I didn't realise that was a requirement - I'll push out a fix for this soon 🙂

**Comment by andrewlock** [comment]
Thanks, this should be available in NuGet shortly as 1.0.0-beta06
