### ISSUE TITLE
[Proposal] Add support for MongoDB.Bson.ObjectId

### ISSUE THREAD

**Issue by auribuo** [andrewlock/StronglyTypedId#54]
It would be really nice to have the option to use [ObjectId](https://docs.mongodb.com/manual/reference/method/ObjectId/) as a backing type, because MongoDb relies a lot on it and it would remove some convertion that otherwise must happen.

**Comment by larsbloch** [comment]
I second this !

**Comment by andrewlock** [comment]
For feature requests like this, I think I've found an answer in the big redesign of the library in this PR: 
- https://github.com/andrewlock/StronglyTypedId/pull/117

The main idea is to make the library much more maintainable while also giving people a mechanism to customise the generated IDs as much as they like. This will make it easy to make changes like this 🙂
