### ISSUE TITLE
Mark generated code as generated code

### ISSUE THREAD

**Issue by ahordijk** [andrewlock/StronglyTypedId#57]
To prevent code analysis warnings and errors. 
Please add [System.CodeDom.Compiler.GeneratedCode(null, null)] to all generated code, with appropriated tool and version number.

**Comment by SteveDunn** [comment]
I added something similar to Vogen recently: https://github.com/SteveDunn/Vogen/pull/126

**Comment by andrewlock** [comment]
Done as part of the refactor in #117. Note that this marks the _whole_ type as generated, even though it might not _all_ be (because you might manually add additional implementation). It's probably ok though IMO, hence implementing it 😄
