### ISSUE TITLE
MongoDB support and MessagePack support

### ISSUE THREAD

**Issue by feritzcan2** [andrewlock/StronglyTypedId#60]
Hello, do you plan to add serialization support for mongodb and MessagePack( binary serializer) . Or do they already exist, I couldnt find...

Thank you

**Comment by feritzcan2** [comment]
No, I guess :(

**Comment by andrewlock** [comment]
> No, I guess :(

Sorry, I've been on holiday, hence the slow reply!

> Do you plan to add serialization support for mongodb and MessagePack( binary serializer)

I don't have any specific plans, but I've got nothing against it if someone creates a PR 🙂

**Comment by andrewlock** [comment]
For feature requests like this, I think I've found an answer in the big redesign of the library in this PR: 
- https://github.com/andrewlock/StronglyTypedId/pull/117

The main idea is to make the library much more maintainable while also giving people a mechanism to customise the generated IDs as much as they like. This will make it easy to make changes like this 🙂
