### ISSUE TITLE
[Proposal] Add Byte and Int16 Support

### ISSUE THREAD

**Issue by arex388** [andrewlock/StronglyTypedId#69]
I occasionally use `byte` and `short` as the backing type for an Id in SQL Server because `int` is just too large for my needs. It would be nice to have support for `byte` and `short` along side `int` and `long` for such scenarios.

Unless I'm missing something, as far as I can tell, I can't make a strongly typed id for those Ids with the current implementation of the library. I'll probably duplicate what the source generator is outputting manually so I can still get a strongly typed id, but it would be nice to have the library take care of those as well.

**Comment by andrewlock** [comment]
Yep, those are on the radar to add, just need to get round to it 🙂

**Comment by MirzaMerdovic** [comment]
@andrewlock if this is up for grabs, I would be happy to give it a go?

**Comment by andrewlock** [comment]
Sorry for the lack of attention on this, I got a bit burnt out over the requests with this library 😬  The good news is that for feature requests like this, I think I've found an answer in the big redesign of the library in this PR:

- https://github.com/andrewlock/StronglyTypedId/pull/117

The main idea is to make the library much more maintainable while also giving people a mechanism to customise the generated IDs as much as they like. This will make it easy to make changes or additions like this 🙂
