### ISSUE TITLE
[Proposal] Explicit cast

### ISSUE THREAD

**Issue by nils-a** [andrewlock/StronglyTypedId#80]
In one of my projects, I am using something similar to *StronglyTypedId* (i.e. all hand-written structs 😁 ) and I stumbled on this this library.
It seems like there is 99% of the work that I manually typed all here. Great project 🎉 

The feature that I am missing at a first glance is the generation of explicit cast operators.
Would you consider adding explicit casts (as an opt-in) feature to the generation?

**Comment by NxSoftware** [comment]
+1

#68 already exists for implicit and explicit cast operators

**Comment by nils-a** [comment]
Perfect, haven't seen that.
Closing this one, in favor of #68.
