### ISSUE TITLE
Are there plans to have a non-beta version of 1.0?

### ISSUE THREAD

**Issue by ShaharPrishMSFT** [andrewlock/StronglyTypedId#88]
Our governance settings limit our usage of beta versions in prod.

Is there a plan of making this version non-beta?

**Comment by andrewlock** [comment]
Probably. But as soon as I do, I can't do breaking changes any more, so it needs a high bar

**Comment by andrewlock** [comment]
I'm going to close this for now, as it will be addressed in the future at some point 😉
