### ISSUE TITLE
[Proposal] Add DebuggerDisplay to generated code

### ISSUE THREAD

**Issue by espenrl** [andrewlock/StronglyTypedId#98]
For increased productivity while debugging, please consider adding DebuggerDisplay attribute.

I always add DebuggerDisplay to my StronglyTypedId structs, but it would be awesome if the generated code added it.

```
[DebuggerDisplay("{Value}")]
[StronglyTypedId]
public partial struct UserId { }
```

**Comment by andrewlock** [comment]
[According to the docs](https://learn.microsoft.com/en-us/dotnet/framework/debug-trace-profile/enhancing-debugging-with-the-debugger-display-attributes#using-the-debuggerdisplayattribute), this shouldn't be necessary if `ToString()` is overridden:

> For example, if a C# object has an overridden ToString(), the debugger will call the override and show its result instead of the standard {<typeName>}. Thus, if you have overridden ToString(), you do not need to use [DebuggerDisplayAttribute](https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.debuggerdisplayattribute). If you use both, the [DebuggerDisplayAttribute](https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.debuggerdisplayattribute) attribute takes precedence over the ToString() override

Given we always override `ToString()`, I don't think we need this? My tests seem to show that it works as-is too: 

![image](https://github.com/andrewlock/StronglyTypedId/assets/18755388/f5c5dbf4-8312-4d84-9214-8de3162de76a)

I'll close this as I don't think it's required, but feel free to re-open it if I'm wrong about something here, thanks!
